package dacortez.netChat;

public enum DataType {
	
	CONNECTION_OK("EP2P/CONNECTION/OK"), 
	LOGIN_REQUEST("EP2P/LOGIN/REQUEST"), 
	LOGIN_OK("EP2P/LOGIN/OK"), 
	LOGIN_FAIL("EP2P/LOGIN/FAIL"),
	USERS_REQUEST("EP2P/USER/REQUEST"), 
	USERS_LIST("EP2P/USERS/LIST"),
	LOGOUT_REQUEST("EP2P/LOGOUT/REQUEST"),
	LOGOUT_OK("EP2P/LOGOUT/OK"),
	CHAT_REQUEST("EP2P/CHAT/REQUEST"),
	CHAT_OK("EP2P/CHAT/OK"),
	CHAT_DENIED("EP2P/CHAT/DENIED"),
	CHAT_MSG("EP2P/CHAT/MSG"),
	CHAT_END("EP2P/CHAT/END"),
	CHAT_FINISHED("EP2P/CHAT/FINISHED"),
	TRANSFER_REQUEST("EP2P/TRANSFER/REQUEST"),
	TRANSFER_OK("EP2P/TRANSFER/OK"),
	TRANSFER_DENIED("EP2P/TRANSFER/DENIED"),
	TRANSFER_START("EP2P/TRANSFER/START"),
	FILE_DATA("EP2P/FILE/DATA"),
	DATA_SAVED("EP2P/DATA/SAVED"),
	SEND_AGAIN("EP2P/SEND/AGAIN"),
	TRANSFER_END("EP2P/TRANSFER/END"),
	HEART_BEAT("EP2P/HEART/BEAT");
	
	private final String value;
	
	private DataType(String value) {
		this.value = value;
	}
	
	@Override
	public String toString() {
		return value;
	}
}
