package dacortez.netChat;

public enum DataType {
	
	CONNECTION_OK("CONNECTION/OK"), 
	LOGIN_REQUEST("LOGIN/REQUEST"), 
	LOGIN_OK("LOGIN/OK"), 
	LOGIN_FAIL("LOGIN/FAIL"),
	USERS_REQUEST("USER/REQUEST"), 
	USERS_LIST("USERS/LIST"),
	LOGOUT_REQUEST("LOGOUT/REQUEST"),
	LOGOUT_OK("LOGOUT/OK"),
	CHAT_REQUEST("CHAT/REQUEST"),
	CHAT_OK("CHAT/OK"),
	CHAT_DENIED("CHAT/DENIED"),
	CHAT_MSG("CHAT/MSG"),
	CHAT_END("CHAT/END"),
	CHAT_FINISHED("CHAT/FINISHED"),
	TRANSFER_REQUEST("TRANSFER/REQUEST"),
	TRANSFER_OK("TRANSFER/OK"),
	TRANSFER_DENIED("TRANSFER/DENIED"),
	TRANSFER_START("TRANSFER/START"),
	FILE_DATA("FILE/DATA"),
	DATA_SAVED("DATA/SAVED"),
	TRANSFER_END("TRANSFER/END"),
	HEART_BEAT("HEART/BEAT");
	
	private final String value;
	
	private DataType(String value) {
		this.value = value;
	}
	
	@Override
	public String toString() {
		return value;
	}
}
